version: '3'
services:
  movietest:
    container_name: movietest
    build:
      context: ./django
    restart: always
    volumes:
      - ${PWD}/django:/opt/project
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
