# Generated by Django 3.2.20 on 2024-01-25 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100, null=True)),
                ('place', models.CharField(max_length=500, null=True)),
                ('masterpiece', models.CharField(max_length=500, null=True)),
                ('award_win', models.IntegerField(blank=True, null=True)),
                ('award_nom', models.IntegerField(blank=True, null=True)),
                ('person_link', models.URLField(max_length=500, null=True)),
                ('award_link', models.URLField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100, null=True)),
                ('place', models.CharField(max_length=500, null=True)),
                ('masterpiece', models.CharField(max_length=500, null=True)),
                ('award_win', models.IntegerField(blank=True, null=True)),
                ('award_nom', models.IntegerField(blank=True, null=True)),
                ('person_link', models.URLField(max_length=500, null=True)),
                ('award_link', models.URLField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'director',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('genres', models.CharField(max_length=100)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('metascore', models.IntegerField(blank=True, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('gross_earning_in_mil', models.FloatField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.actor')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.director')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
